# -- 코드를 입력하세요
# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR AS A
# LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
# ON A.CAR_ID = B.CAR_ID
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C 
# ON A.CAR_TYPE = C.CAR_TYPE
# WHERE A.CAR_TYPE IN('세단', 'SUV')
# AND B.START_DATE <= '2022-11-01'
# AND B.END_DATE >='2022-11-30'
WITH T AS 
(SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR AS A 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
WHERE (A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV')
    AND (B.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE '2022-11-01' BETWEEN START_DATE AND END_DATE) 
    AND B.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE '2022-11-30' BETWEEN START_DATE AND END_DATE)
    AND B.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-30')))

SELECT DISTINCT H.CAR_ID, H.CAR_TYPE, ROUND(H.FEE,0)
FROM (
    SELECT T.CAR_ID, C.CAR_TYPE, T.DAILY_FEE * (1-C.DISCOUNT_RATE * 0.01) * 30 AS FEE
    FROM T INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C 
    ON T.CAR_TYPE = C.CAR_TYPE
    WHERE C.DURATION_TYPE = '30일 이상') AS H
WHERE H.FEE BETWEEN 500000 AND 2000000
ORDER BY H.FEE DESC, H.CAR_TYPE ASC, H.CAR_ID DESC